version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+asyncpg://test_task:test_task@postgres:5432/test_task
    restart: unless-stopped
  
  postgres:
    image: postgres:14.17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_task
      - POSTGRES_USER=test_task
      - POSTGRES_PASSWORD=test_task
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped