version: '3.8'

services:
  web:
    build: .
    user: appuser
    ports:
      - "8080:8080"
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        echo 'Running migrations...' &&
        make migrate &&
        echo 'Starting application...' &&
        uvicorn src.main:app --host 0.0.0.0 --port 8080
      "
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+asyncpg://test_task:test_task@postgres:5432/test_task
    restart: unless-stopped
  
  postgres:
    image: postgres:14.17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_task
      - POSTGRES_USER=test_task
      - POSTGRES_PASSWORD=test_task
    volumes:
      - postgres-avito-test:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-avito-test: